name       : xcape
version    : 1.2
release    : 4
source     :
    - https://github.com/alols/xcape/archive/v1.2.tar.gz : a27ed884fd94f03058af65a39edfe3af3f2f8fbb76ba9920002a76be07fb2821
license    : GPL-3.0-or-later
component  : system.utils
summary    : xcape allows you to use a modifier key as another key when pressed and released on its own.
description: |
    xcape allows you to use a modifier key as another key when pressed and released on its own.
builddeps  :
    - pkgconfig(xtst)
rundeps    :
    - xmodmap
build      : |
    %make MANDIR=/share/man/man1
install    : |
    %make_install MANDIR=/share/man/man1
